import Head from 'next/head';
import { useState } from 'react';
import axios from 'axios';

import styles from '../styles/Home.module.css';
export default function Home() {
	const [inputDate, setInputDate] = useState("");
	const [dataRes, setDataRes] = useState();
	const [isCopied, setIsCopied] = useState(false);

	const[error, setError] =useState("")
	const onSubmit =async(e) => {
		e.preventDefault();
	
		

		const url =`http://localhost:3000/api/${inputDate}`
		const res = await axios.get(url);
		console.log(res.data)
			setDataRes(res.data);
			setInputDate("")
		  

	};
	
  const handleCopy = () => {
    navigator.clipboard.writeText(dataRes).then(
      () => {
        setIsCopied(true);
      },
      () => {
        console.error('Failed to copy text');
      }
    );
  };
	
	return (
		<div className={styles.container}>
			<Head>
				<title>time microservice</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main >
				<h1>Time Microservice</h1>
				<div className={styles.main}>
				<form className={styles.wrapper} onSubmit={onSubmit}>
					
					<input typeof="date" placeholder="add date eg. 2015-02-02 or unix" value={inputDate} onChange={(e)=>setInputDate(e.target.value)} />

					<button type="submit" >
						
						submit
					</button>
				</form>
				<br />
					{dataRes != null ?  <div className={styles.result}>
						<p>Time in unix : <span>{dataRes.unix }</span></p>
						<p>Time in utc :  <span>{dataRes.utc}</span></p>
						 <button onClick={handleCopy}>
                            {isCopied ? 'Copied' : 'Copy'}
                         </button>
					</div> : <div>
							
					</div>
					}
					{dataRes?.error != null && <p style={{color:"red",backgroundColor:"yellow", padding:"10px 20px", fontSize:"18px"}}>{ dataRes.error}</p>}
				</div>
			</main>
		</div>
	);
}
